param(
  [switch]$ConfirmCreate,
  [switch]$ConfirmRebuild,
  [string]$ServiceName = 'postgresql-heavenly-test',
  [string]$PostgresRoot = 'C:\Program Files\PostgreSQL\17',
  [int]$Port = 55432,
  [string]$DatabaseName = 'hc_lite',
  [string]$DatabaseUser = 'hc_lite_app'
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$dataDirectory = Join-Path $PostgresRoot 'data'
$psqlPath = Join-Path $PostgresRoot 'bin\psql.exe'
$pgCtlPath = Join-Path $PostgresRoot 'bin\pg_ctl.exe'
$hbaPath = Join-Path $dataDirectory 'pg_hba.conf'
$envPath = Join-Path $projectRoot '.env.local'

if (-not $ConfirmCreate -and -not $ConfirmRebuild) {
  throw 'Use -ConfirmCreate for a new database or -ConfirmRebuild to replace an existing hc_lite database.'
}
if ($DatabaseName -notmatch '^[a-z_][a-z0-9_]*$' -or $DatabaseUser -notmatch '^[a-z_][a-z0-9_]*$') {
  throw 'Database name and role must be lowercase PostgreSQL identifiers.'
}
foreach ($requiredPath in @($psqlPath, $pgCtlPath, $hbaPath)) {
  if (-not (Test-Path -LiteralPath $requiredPath)) { throw "Missing PostgreSQL file: $requiredPath" }
}
if ((Get-Service -Name $ServiceName -ErrorAction Stop).Status -ne 'Running') {
  throw "PostgreSQL service is not running: $ServiceName"
}

function New-RandomHex([int]$bytes) {
  $buffer = [byte[]]::new($bytes)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
  return ([Convert]::ToHexString($buffer)).ToLowerInvariant()
}

function New-RandomBase64([int]$bytes) {
  $buffer = [byte[]]::new($bytes)
  [System.Security.Cryptography.RandomNumberGenerator]::Fill($buffer)
  return [Convert]::ToBase64String($buffer)
}

function Invoke-Psql {
  param([string]$User, [string]$Database, [string]$Sql, [string]$Password = '')
  $previous = $env:PGPASSWORD
  try {
    $env:PGPASSWORD = $Password
    $output = & $psqlPath -X -v ON_ERROR_STOP=1 -h 127.0.0.1 -p $Port -U $User -d $Database -Atq -c $Sql 2>&1
    if ($LASTEXITCODE -ne 0) { throw "psql failed: $($output -join [Environment]::NewLine)" }
    return $output
  } finally {
    $env:PGPASSWORD = $previous
  }
}

function Reload-Postgres {
  $output = & $pgCtlPath reload -D $dataDirectory 2>&1
  if ($LASTEXITCODE -ne 0) { throw "PostgreSQL reload failed: $($output -join [Environment]::NewLine)" }
  Start-Sleep -Milliseconds 500
}

$databasePassword = New-RandomHex 24
$sessionSecret = New-RandomHex 32
$configKey = New-RandomBase64 32
$originalHba = [IO.File]::ReadAllText($hbaPath)
$rollbackPath = "$hbaPath.hclite-rollback"
[IO.File]::WriteAllText($rollbackPath, $originalHba, [Text.UTF8Encoding]::new($false))

try {
  $temporaryRule = "host all postgres 127.0.0.1/32 trust`r`n"
  [IO.File]::WriteAllText($hbaPath, $temporaryRule + $originalHba, [Text.UTF8Encoding]::new($false))
  Reload-Postgres

  $databaseExists = @(Invoke-Psql -User postgres -Database postgres -Sql "SELECT 1 FROM pg_database WHERE datname = '$DatabaseName'") -contains '1'
  if ($databaseExists -and -not $ConfirmRebuild) {
    throw "Database already exists: $DatabaseName. Use -ConfirmRebuild to replace it."
  }

  $roleExists = @(Invoke-Psql -User postgres -Database postgres -Sql "SELECT 1 FROM pg_roles WHERE rolname = '$DatabaseUser'") -contains '1'
  if (-not $roleExists) {
    Invoke-Psql -User postgres -Database postgres -Sql "CREATE ROLE $DatabaseUser LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION"
  }
  if ($databaseExists) {
    Invoke-Psql -User postgres -Database postgres -Sql "DROP DATABASE $DatabaseName WITH (FORCE)"
  }
  Invoke-Psql -User postgres -Database postgres -Sql "ALTER ROLE $DatabaseUser WITH LOGIN PASSWORD '$databasePassword'"
  Invoke-Psql -User postgres -Database postgres -Sql "CREATE DATABASE $DatabaseName OWNER $DatabaseUser"
} finally {
  [IO.File]::WriteAllText($hbaPath, $originalHba, [Text.UTF8Encoding]::new($false))
  Reload-Postgres
  Remove-Item -LiteralPath $rollbackPath -Force -ErrorAction SilentlyContinue
}

$databaseUrl = "postgresql://${DatabaseUser}:${databasePassword}@127.0.0.1:${Port}/${DatabaseName}"
$contents = @"
# Generated by scripts/setup-local-postgres.ps1. Local only; never commit.
DATABASE_URL=$databaseUrl
SESSION_SECRET=$sessionSecret
CONFIG_ENCRYPTION_KEY=$configKey
APP_ORIGIN=http://127.0.0.1:3000
COOKIE_SECURE=false
TRUST_PROXY=false
FFMPEG_PATH=.local-tools/ffmpeg.exe
STT_MAX_UPLOAD_BYTES=524288000
STT_MAX_CONCURRENT_PER_USER=1
TEXT_MAX_CONCURRENT_PER_USER=2
"@
[IO.File]::WriteAllText($envPath, $contents.TrimStart(), [Text.UTF8Encoding]::new($false))

$env:DATABASE_URL = $databaseUrl
Push-Location $projectRoot
try {
  & node scripts/migrate-database.mjs
  if ($LASTEXITCODE -ne 0) { throw 'HCLite database migration failed.' }
} finally {
  Pop-Location
}

Invoke-Psql -User $DatabaseUser -Password $databasePassword -Database $DatabaseName -Sql 'SELECT current_database(), current_user' | Out-Null
Write-Output "HCLite PostgreSQL is ready: $DatabaseName on port $Port"
Write-Output "Environment file: $envPath"
Write-Output 'Local PostgreSQL authentication has been restored to its original configuration.'
